// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAepqa4I_rqlftR2T8dQ-OmWMQ-g7KN_6g',
    appId: '1:196278556177:web:65cf5aa6d898b3aa35c3b0',
    messagingSenderId: '196278556177',
    projectId: 'dashboard-bf502',
    authDomain: 'dashboard-bf502.firebaseapp.com',
    databaseURL: 'https://dashboard-bf502-default-rtdb.firebaseio.com',
    storageBucket: 'dashboard-bf502.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-Hr3UK6muv7TtyoYf3uUWoOBR-yQUgbw',
    appId: '1:196278556177:android:35df6f6c1d34677a35c3b0',
    messagingSenderId: '196278556177',
    projectId: 'dashboard-bf502',
    databaseURL: 'https://dashboard-bf502-default-rtdb.firebaseio.com',
    storageBucket: 'dashboard-bf502.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWBl8cLU372fCYRNASxvO0cq11rhf6Ht8',
    appId: '1:196278556177:ios:27c2b98496e59e2e35c3b0',
    messagingSenderId: '196278556177',
    projectId: 'dashboard-bf502',
    databaseURL: 'https://dashboard-bf502-default-rtdb.firebaseio.com',
    storageBucket: 'dashboard-bf502.appspot.com',
    iosClientId: '196278556177-ueb4i9n9ep3sqplh4ff3rmpb41pch40u.apps.googleusercontent.com',
    iosBundleId: 'com.example.dashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWBl8cLU372fCYRNASxvO0cq11rhf6Ht8',
    appId: '1:196278556177:ios:27c2b98496e59e2e35c3b0',
    messagingSenderId: '196278556177',
    projectId: 'dashboard-bf502',
    databaseURL: 'https://dashboard-bf502-default-rtdb.firebaseio.com',
    storageBucket: 'dashboard-bf502.appspot.com',
    iosClientId: '196278556177-ueb4i9n9ep3sqplh4ff3rmpb41pch40u.apps.googleusercontent.com',
    iosBundleId: 'com.example.dashboard',
  );
}
